### ISSUE TITLE
Replace Portable packages.

### ISSUE THREAD

**Issue by Shmellyorc** [tainicom/Aether.Physics2D#110]
The main problem is using "portable packages". They are not being used any more and will make your lovely and awesome physics framework pretty obsolete. I had real carnage when I bought in any Aether packages from monogame 3.8 (not a prerelease, but the current version of monogame)

Past few years now since .net 5, Microsoft is been moving towards dotnet core and standard is their "ecosystems".

- I couldn't use any of my content pipeline since monogame 3.8, uses that uses current .net, dotnet core, or dotnet standards.
- It pretty much put my whole project in lockdown because after I removed it, it messed a bunch with my content pipeline stuff. So I had to do a clean wipe using "dotnet clean" which was another problem since I had to rebuild my content pipeline library to be used in the Monogame MGCB builder.
- The portable will not work on the new standards of cross platform ecosystems because they are severely out of date. Current cross platform is used with dotnet core / dotnet standard using this new standard. Anyone using your Aether packages which uses "monogame portable" will not work on a Linux or Mac.

@nkast @tainicom Please review this, it is important: https://docs.monogame.net/articles/whats_new.html#removed-portable-assemblies

**Comment by nkast** [comment]
The portable package is used to build the library against the MonoGame API.
Additionally the nuget of physics2D does not include the dependency to the portable MG library.

Probably one of your other libraries is leaking the wrong dll to the output directory,
for example one of your libraries is referencing the MonoGame DX, while other libraries are
referencing the  MonoGame GL. 
You need to setup the content project so that the MonoGame dll does not get copied to the output directory. 

The documentation above mention this as well and gives an example about setting PrivateAssets, ExcludeAssets, etc.
