### ISSUE TITLE
Weird collision behavior.

### ISSUE THREAD

**Issue by mjr27** [tainicom/Aether.Physics2D#27]
While playing with this library for a home-grown project, i stuck on a weird behavior.

Sometimes (but in consistent manner) one of collided bodies loses momentum on one of axises.

Debugging put me deep within `Island.Solve()` , but my math skills are far from what was needed for this task.

So i just put a reproducible example below.

```c#
        [TestMethod]
        public void TestReflectCollision()
        {
            var position = Vector2.One;
            var speed = Vector2.One * -10.6f;
            var dT = 0.0016666f;

            var world = new World(Vector2.Zero);

            var wall = world.CreateRectangle(2F, 20f, 1f, new Vector2(-1F, 10f));
            wall.SetRestitution(1);
            wall.SetFriction(0);
            wall.FixedRotation = true;
            wall.IsBullet = true;


            var ball = world.CreateCircle(0.51f, 1f, position, BodyType.Dynamic);
            ball.LinearVelocity = speed;
            ball.SetRestitution(1);
            ball.SetFriction(0);
            ball.FixedRotation = true;
            ball.IsBullet = true;

            world.Step(dT*28);
            Assert.IsTrue(ball.LinearVelocity.X < -10 && ball.LinearVelocity.Y < -10, ball.LinearVelocity.ToString());
            world.Step(dT);

            // this one fails; LinearVelocity.X is zero
            Assert.IsTrue(ball.LinearVelocity.X > 10 && ball.LinearVelocity.Y <-10, ball.LinearVelocity.ToString());
        }
```

Gist: https://gist.github.com/mjr27/a0d4b2d79caf9ed56fce0f929dcefaa4

**Comment by nkast** [comment]
Thanks for the test @mjr27 
I recall that a similar issue was reported several times in the past. I found one or two reports of this here:
https://farseerphysics.codeplex.com/workitem/34553
https://farseerphysics.codeplex.com/discussions/456718
https://vimeo.com/74416243

From a first read I get that the bug was introduces somewhere between Farseer 3.3.1 and 3.5 and has to do with CCD, Contacts and Settings.VelocityThreshold.

The hard part now is to identify which commit introduced the bug (over the course of two years ! ) and compare the changes with the official Box2D to see what's the correct behavior.

**Comment by nkast** [comment]
Here are some early finding:

* Bug does not appear when I comment out the line `if (vRel < -Settings.VelocityThreshold || vRel > 0)`.
* Bug does not appear when CCD is turned off.
* Bug does not appear when both wall and ball have IgnoreCCD = true.
* The bug still exists when both bodies have IsBullet = false.

Obviously the bug -or what triggers the bug conditions- can be traced down to SloverTOI().

**Comment by nkast** [comment]
@mjr27 , can you verify that PR #29 fixed that issue?

FYI, @Genbox.

**Comment by mjr27** [comment]
Works like charm. Thanks!
