### ISSUE TITLE
QuadTree.RayCast nullpointer error

### ISSUE THREAD

**Issue by ldelgiud** [tainicom/Aether.Physics2D#69]
While using this library for a personal project I noticed that in Physics2D/Collision/QuadTree.cs line 240 sometimes returns a null-pointer exception, I believe the reason is that line 239 is supposed to be `if (qt.IsPartitioned)` instead of `if (IsPartitioned)` or at least that's how I fixed it.

**Comment by nkast** [comment]
You are probably right, the code check the root qtree instead of the current qt that the rest of the loop operates on.

I haven'd looked much at QuadTreeBroadphase until now. It looks like it produces a ton of memory garbage. I don't think it's a good idea to use it in production.
A faster approach for a dynamic QTree  would be with a hashSet + morton key. I don't know if that qualifies as a Q-Tree, it's far from a tree structure. Anyways, a true Q-tree should be implemented into a struct array, to avoid memory garbage and improve memory management and cache use. But I don't think this implementation will beat the currently dynamic tree, but I might be wrong.

Also the World .ctor() now takes an AABB, and doesn't allow for custom IBroadphase.
Two option here: 
Allow any custom implementations of IBroadphase, 
or remove IBroadphase and QTree altogether.  
I have to see what impact has the interface on performance and weight in the pros and cons.
